---
- name: "Playbook 1"
  hosts: cisco
  connection: network_cli

  vars:
    ansible_network_os: cisco.ios.ios
    ansible_user: admin
    ansible_password: admin

  tasks:
    - name: "Task 1 - Send a Show Command"
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
      register: result

    - name: "Task 2 - Print the output"
      debug:
        msg: "{{ result.stdout_lines }}"